// File generated by FlutterFire CLI.
// This is a placeholder file. You need to run 'flutterfire configure'
// to generate the actual configuration.
// See: https://firebase.google.com/docs/flutter/setup

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Demo project configuration for emulators
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: '1:123456789:web:abc123',
    messagingSenderId: '123456789',
    projectId: 'demo-petkeeper',
    authDomain: 'demo-petkeeper.firebaseapp.com',
    storageBucket: 'demo-petkeeper.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFfihzEyCfQb1O7Sy8ynbz9xhYxNH-sVw',
    appId: '1:341762936537:android:3b5d886e7b0d429515f8c8',
    messagingSenderId: '341762936537',
    projectId: 'petkeeper-lite-1002',
    storageBucket: 'petkeeper-lite-1002.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuT1QJOAMrbJUQr8TW0sfDFqh6zAwM7Gg',
    appId: '1:341762936537:ios:b76e1404edbec86615f8c8',
    messagingSenderId: '341762936537',
    projectId: 'petkeeper-lite-1002',
    storageBucket: 'petkeeper-lite-1002.firebasestorage.app',
    androidClientId: '341762936537-hvmvpfjr2rvmmbs51vhpoao0i71oikco.apps.googleusercontent.com',
    iosClientId: '341762936537-4q8qpcjoh03caau5ei39ckvvm071fsel.apps.googleusercontent.com',
    iosBundleId: 'com.petkeeper.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: '1:123456789:macos:abc123',
    messagingSenderId: '123456789',
    projectId: 'demo-petkeeper',
    storageBucket: 'demo-petkeeper.appspot.com',
    iosBundleId: 'com.petkeeper.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: '1:123456789:windows:abc123',
    messagingSenderId: '123456789',
    projectId: 'demo-petkeeper',
    storageBucket: 'demo-petkeeper.appspot.com',
  );
}